### ISSUE TITLE
缺少依赖 react-router 、semi-icon

### ISSUE THREAD

**Issue by hemengke1997** [xieyezi/semi-design-pro#1]
安装的 react-router@6.0.0-beta.8，启动后报错，说没有导出 `useNavigate`。
请问作者是安装的哪个版本的 react-router
谢谢

**Comment by xieyezi** [comment]
@hemengke1997 
"react-router-dom": "6.0.0-beta.0",
semi-icon是组件自带的，请确认一下是否正常安装semi

**Comment by zzlhr** [comment]
我用pnpm跟楼主同样问题，删除node_modules，改用yarn就可以了

**Comment by xieyezi** [comment]
@zzlhr 谢谢给出解答，原来你们都是用的 `pnpm`
