### ISSUE TITLE
package.json 不规范

### ISSUE THREAD

**Issue by tufeiping** [xieyezi/semi-design-pro#16]
能否自己跑一下-_-||

多了两个**逗号**

{
  "name": "semi-admin",
  "version": "1.0.0",
  "scripts": {
    "dev": "vite",
    "start": "vite",
    "preview": "vite preview",
    "build:dev": "tsc && vite build --mode dev",
    "build:test": "tsc && vite build --mode test",
    "build:prod": "tsc && vite build --mode prod",
    "prepare": "husky install",
    "pre-commit": "yarn lint-staged",
    "lint": "tsc --noEmit &&  eslint src --ext .ts,.tsx",
    "lint:fix": "tsc --noEmit && eslint --fix --ext src --ext .ts,.tsx",
    "format": "prettier --write \"src/**/*.ts\" \"src/**/*.tsx\" \"src/**/*.scss\" \"mock/**/*.ts\""**,**
  },
  "dependencies": {
    "@douyinfe/semi-ui": "^2.1.1",
    "axios": "^0.24.0",
    "driver.js": "^0.9.8",
    "echarts": "^5.2.2",
    "echarts-for-react": "^3.0.0",
    "history": "^5.0.1",
    "husky": "^7.0.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-intl": "^5.21.0",
    "react-router-dom": "6.0.2",
    "zustand": "^3.6.1"
  },
  "devDependencies": {
    "@types/node": "^16.11.6",
    "@types/qs": "^6.9.7",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@typescript-eslint/eslint-plugin": "^5.2.0",
    "@typescript-eslint/parser": "^5.2.0",
    "@vitejs/plugin-react": "^1.0.0",
    "eslint": "^8.1.0",
    "lint-staged": "^11.2.6",
    "mockjs": "^1.1.0",
    "prettier": "^2.4.1",
    "qs": "^6.10.1",
    "sass": "^1.43.4",
    "scss": "^0.2.4",
    "typescript": "^4.3.2",
    "vite": "^2.6.4",
    "vite-plugin-mock": "^2.9.6"
  }**,**
}

**Comment by xieyezi** [comment]
@tufeiping 应该是因为format的问题，已修改，感谢修正！

**Comment by xieyezi** [comment]
@tufeiping 刚刚和小伙伴通过了一下，是因为我们在尝试使用github actions进行部署，不小心把package.json文件修改了，现在已经修正！
